# Generated by Django 2.2.28 on 2023-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lieu',
            options={'verbose_name_plural': 'Lieux'},
        ),
        migrations.AlterField(
            model_name='lieu',
            name='disponibilite',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Occupé', 'Occupé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='etat',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Affamé', 'Affamé'), ('Repus', 'Repus'), ('Blessé', 'Blessé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='niveau',
            field=models.CharField(choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Fort', 'Fort')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Plante', 'Plante'), ('Sol', 'Sol'), ('Eau', 'Eau'), ('Feu', 'Feu')], max_length=20),
        ),
    ]
